language: objective-c
osx_image: xcode7

env:
    - TEST_CONFIG="RELEASE"
    - TEST_CONFIG="CARTHAGE"

before_install:
    - if [[ "$TEST_CONFIG" == "RELEASE" ]]; then gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet; fi
    - if [[ "$TEST_CONFIG" == "CARTHAGE" ]]; then brew install carthage; fi

install:
    - if [[ "$TEST_CONFIG" == "RELEASE" ]]; then git submodule update -i --recursive; fi

script:
    - set -o pipefail
    - if [[ "$TEST_CONFIG" == "RELEASE" ]]; then xcodebuild -project Swiftx.xcodeproj -scheme Swiftx -sdk macosx ONLY_ACTIVE_ARCH=NO clean build test | xcpretty -c -f `xcpretty-travis-formatter`; fi
    - if [[ "$TEST_CONFIG" == "RELEASE" ]]; then xcodebuild -project Swiftx.xcodeproj -scheme Swiftx-iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean build test | xcpretty -c -f `xcpretty-travis-formatter`; fi
    - if [[ "$TEST_CONFIG" == "CARTHAGE" ]]; then carthage update --verbose --no-use-binaries --configuration Debug && carthage build --no-skip-current; fi

